# Site settings
title: Trading Card App Ltd
email: admin@tradingcardapps.com
description: We build TCG Companion — the modern app for trading card collectors.
baseurl: ""
url: "https://tradingcardapps.com"
app_url: "https://tcgcompanion.app"

# Build settings
markdown: kramdown
